apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  count: 1
  elasticsearchRef:
    name: elasticsearch
  enterpriseSearchRef: {}
  http:
    service:
      metadata: {}
      spec:
        ports:
          - name: https
            port: 443
            protocol: TCP
            targetPort: 5601
        type: NodePort
    tls:
      certificate: {}
      selfSignedCertificate:
        disabled: true
  monitoring:
    logs: {}
    metrics: {}
  podTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
  version: 8.8.1
