apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  labels:
    k8s-app: fluent-bit-logging
spec:
  ports:
    - name: http-metrics
      port: 2020
      protocol: TCP
      targetPort: 2020
  type: NodePort
  selector:
    k8s-app: fluent-bit-logging