apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-route
spec:
  hosts:
  - nginx-service.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: nginx-service.default.svc.cluster.local
        subset: v1