apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- wordpress-ingress.yaml
- ../../base
patches:
- path: patch-mysql-pvc.yaml
- path: patch-wordpress-pvc.yaml
- path: patch-wordpress-configmap.yaml
- path: patch-wordpress-deployment.yaml
#nameSuffix: -dev