apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  template:
    spec:
      containers:
      - name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: PHP_INI_SCAN_DIR
          value: /usr/local/etc/php/conf.d/php
        volumeMounts:
        - name: wordpress-php-config
          mountPath: /usr/local/etc/php/conf.d/php.ini
          $patch: delete
        - name: wordpress-php-config
          mountPath: /usr/local/etc/php/conf.d/php
