apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- literals:
  - password=f96FGngBtm
  name: mysql-pass
resources:
- mysql-deployment.yaml
- wordpress-deployment.yaml
- wordpress-php-config.yaml
generatorOptions:
  disableNameSuffixHash: true
