  apiVersion: v1
  kind: Service
  metadata: 
    name: mongo-db
    labels: 
      app: mongo-db
  spec: 
    ports: 
      - name: mongodb
        port: 27017
    type: ClusterIP
    selector: 
      app: mongo-db