apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apisix
  labels:
    app: apisix
spec:
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      securityContext:
        runAsUser: 636
        runAsGroup: 636
        fsGroup: 636
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: apisix
          image: apache/apisix:3.9.1-debian
          ports:
            - name: http
              containerPort: 9080
              hostPort: 80
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
          resources:
            requests:
              cpu: "0.1"
              memory: "220Mi"
            limits:
              cpu: "0.5"
              memory: "614Mi"
          livenessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /apisix/status
              port: 9080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: apisix-config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: apisix.conf.yaml
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: apisix-config
          secret:
            secretName: apisix
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0