apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apisix
  labels:
    app.iyes.dev/name: apisix
spec:
  template:
    spec:
      containers:
        - $patch: merge
          name: apisix
          volumeMounts:
            - name: ngx-tpl-config
              mountPath: /usr/local/apisix/apisix/cli/ngx_tpl.lua
              subPath: ngx_tpl.lua
      volumes:
        - $patch: merge
          name: ngx-tpl-config
          configMap:
            name: ngx-tpl
      