apiVersion: v1
kind: Service
metadata:
  name: apisix
spec:
  type: NodePort
  selector:
    app.iyes.dev/name: apisix
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32350
