apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apisix
  labels:
    app.iyes.dev/name: apisix
spec:
  template:
    spec:
      volumes:
        - name: ngx-tpl-config
          configMap:
            name: ngx-tpl
      