apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apisix
  labels:
    app: apisix
spec:
  template:
    spec:
      containers:
        - name: apisix
          volumeMounts:
            - name: ngx-tpl-config
              mountPath: /usr/local/apisix/apisix/cli/ngx_tpl.lua
              subPath: ngx_tpl.lua
      volumes:
        - name: ngx-tpl-config
          secret:
            secretName: ngx-tpl
      