apiVersion: v1
kind: Service
metadata:
  name: apisix
spec:
  type: NodePort
  selector:
    app: apisix
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32350
