apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi