apiVersion: apps/v1
kind: Deployment
metadata:
  name:  etcd
  labels:
    app: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.4.18
        resources:
            requests:
              cpu: "0.1"
              memory: "100Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"
        command: ["/usr/local/bin/etcd", "--config-file", "/root/etcd.conf.yml"]
        livenessProbe:
          tcpSocket:
            port: 2379
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 2379
          name: etcd
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: data
          mountPath: /data
        - name: conf
          subPath: etcd.conf.yaml
          mountPath: /root/etcd.conf.yml
      volumes:
        - name: conf
          configMap:
            name: etcd
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: data
          persistentVolumeClaim:
            claimName: etcd
      restartPolicy: Always
