apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - files:
      - apisix.conf.yaml
    name: apisix
  - files:
      - apisix-dashboard.conf.yaml
    name: apisix-dashboard
  - files:
      - etcd.conf.yaml
    name: etcd
  - files:
      - ngx_tpl.lua
    name: apisix

resources:
  - apisix-daemonset.yaml
  - apisix-service.yaml
  - apisix-dashboard-deployment.yaml
  - apisix-dashboard-service.yaml
  - etcd-service.yaml
  - etcd-deployment.yaml
  - etcd-pvc.yaml

patchesStrategicMerge:
  - apisix-daemonset-add-volumes.yml