apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - files:
      - apisix.conf.yaml
    name: apisix
  - files:
      - apisix-dashboard.conf.yaml
    name: apisix-dashboard

resources:
  - apisix-daemonset.yaml
  - apisix-service.yaml
  - apisix-dashboard-deployment.yaml
  - apisix-dashboard-service.yaml
