resources:
  - nginx-v1-deployment.yaml
  - nginx-v2-deployment.yaml
  - nginx-service.yaml

configMapGenerator:
  - files:
      - configs/nginx.conf
    name: nginx-config-configmap
  - files:
      - configs/index-v1.html
      - configs/index-v2.html
    name: nginx-html-configmap