resources:
  - v1-deployment.yaml
  - v2-deployment.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
  - files:
      - configs/nginx.conf
    name: nginx-config-configmap
  - files:
      - configs/index-v1.html
      - configs/index-v2.html
    name: nginx-html-configmap
