apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- v1-deployment.yaml
# - v2-deployment.yaml
- service.yaml
- pdb.yaml
- hpa.yaml

configMapGenerator:
- files:
  - configs/nginx.conf
  name: nginx-config-configmap
- files:
  - configs/index-v1.html
  - configs/index-v2.html
  name: nginx-html-configmap
- files:
  - configs/conf.d/default.conf
  name: nginx-confd-configmap

patchesStrategicMerge:
- configmap.yaml