apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources: 
            limits:
              cpu: 250m
              memory: 64Mi
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      initContainers:
        - name: install-net-tools
          image: busybox
          command: ['sh', '-c', 'apk add --no-cache net-tools']
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-configmap