apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1
  labels:
    app: nginx
    version: v1
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          resources: 
            limits:
              cpu: 250m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index-v1.html
            - name: nginx-confd
              mountPath: /etc/nginx/conf.d
            - name: nginx-cache
              mountPath: /var/cache/nginx
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config-configmap
        - name: nginx-html
          configMap:
            name: nginx-html-configmap
        - name: nginx-confd
          configMap: 
            name: nginx-confd-configmap
        - name: nginx-cache
          emptyDir: {}
            