apiVersion: v2
appVersion: "1.0"
home: https://archerydms.com/
description: Archery Helm chart for Kubernetes
name: archery
version: 0.2.0
sources:
  - https://github.com/hhyo/Archery

maintainers:
  - name: AceRyuunosuke
    email: aozakiaoko@outlook.com

dependencies:
  - name: redis
    version: ~16.11.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.embedded
  - name: mysql
    version: ~9.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.embedded
