apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app.kubernetes.io/name: elasticsearch-logstash
    app.kubernetes.io/component: logstash
data:
  logstash.yml: |
    http.host: 0.0.0.0
    pipeline.ecs_compatibility: disabled
  pipelines.yml: |
    - pipeline.id: logstash
      path.config: "/usr/share/logstash/pipeline/logstash.conf"
 
  log4j2.properties: |
    logger.logstashpipeline.name = logstash.inputs.beats
    logger.logstashpipeline.level = error
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  labels:
    app.kubernetes.io/name: elasticsearch-logstash
    app.kubernetes.io/component: logstash
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [log][file][path] =~ /\/var\/log\/containers\/apisix-.*_apisix_apisix-.*.log$/ {
        grok {
          match => { 
            "message" => "%{IP:remote} %{DATA:host} %{USERNAME:user} \[%{HTTPDATE:time}\] %{HOSTNAME:http_host} \"%{WORD:method} %{URIPATHPARAM:path} HTTP/.+\" %{NUMBER:code} %{NUMBER:size} %{NUMBER:request_time} \"%{DATA:referrer}\" \"%{DATA:agent}\" %{DATA:upstream_addr} %{NUMBER:upstream_status} %{NUMBER:upstream_response_time} \"%{DATA:upstream_http_referer}\"" 
          }
          named_captures_only => "true"
          overwrite => [ "agent", "host" ]
        }
        date {
          match => [ "time", "dd/MMM/yyyy:HH:mm:ss Z" ]
          target => "@timestamp"
        }
        prune {
          whitelist_names => [ "@timestamp", "remote", "host", "user", "http_host", "method", "path", "code", "size", "request_time", "referrer", "agent", "upstream_addr", "upstream_status", "upstream_response_time", "upstream_http_referer" ]
        }
        mutate { 
          add_field => { 
            "[@metadata][target_index]" => "nginx-access-logstash"
          } 
        }
      } else {
        mutate { 
          add_field => { 
            "[@metadata][target_index]" => "logstash" 
          } 
        }
      }
    }
    output {
      if [@metadata][target_index] == "nginx-access-logstash" {
        elasticsearch {
          index => "nbcdn_access-%{+YYYY.MM.dd}"
          template_name => "template-nbcdn_access"
          ilm_enabled => "true"
          ilm_rollover_alias => "nbcdn_access"
          ilm_pattern => "{now/d}-000001"
          ilm_policy => "nginx-access-policy"
          hosts => [ "${ES_HOSTS}" ]
          user => "${ES_USER}"
          password => "${ES_PASSWORD}"
          cacert => '/etc/logstash/certificates/ca.crt'
        }
      }
      if [@metadata][target_index] == "logstash" {
        elasticsearch {
          index => "logstash-%{+YYYY.MM.dd}"
          template_name => "logstash"
          ilm_enabled => "true"
          ilm_rollover_alias => "logstash"
          ilm_pattern => "{now/d}-000001"
          ilm_policy => "logstash-policy"
          hosts => [ "${ES_HOSTS}" ]
          user => "${ES_USER}"
          password => "${ES_PASSWORD}"
          cacert => '/etc/logstash/certificates/ca.crt'
        }
      }
    }