apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - name: tcp-client
      protocol: TCP
      port: 9092
      targetPort: client
  selector:
    app: kafka
  type: ClusterIP